### PR TITLE
Adding IP and location information to mainnet bootnodes

### PR DESCRIPTION
**Pull request by pcaversaccio**
Driven by my initiative [here](https://ethresear.ch/t/execution-consensus-client-bootnodes/14588) about the execution and consensus of client bootnodes, I would like to increase transparency about the current IPs and geographical distribution and add this information with this PR. The original analysis can be found [here](https://gist.github.com/pcaversaccio/d028b0418192216dc59717ca65c59943).

### CODE REVIEW

**Comment by pcaversaccio** [comment]
@zah @terencechain

**Comment by arnetheduck** [comment]
while I don't have anything specifically against this extra documentation apart from a slightl increase in maintenance to add a new one, a point of order would be that it duplicates the information already present in the ENR - ie it's an interesting point for the curious, but it also doesn't materially affect the network in any major way, beyond new joiners having to manually specify an extra boot node should _all_ the above boot nodes be down, an event that would likely also result in new client releases to update the "default" bootnodes of all clients.

**Comment by pcaversaccio** [comment]
> while I don't have anything specifically against this extra documentation apart from a slightl increase in maintenance to add a new one, a point of order would be that it duplicates the information already present in the ENR - ie it's an interesting point for the curious, but it also doesn't materially affect the network in any major way, beyond new joiners having to manually specify an extra boot node should _all_ the above boot nodes be down, an event that would likely also result in new client releases to update the "default" bootnodes of all clients.

Without going into much detail, it's all about transparency. I have started a lengthy discussion a while ago on the Execution and Consensus Client Bootnodes in the ethresear.ch and Lido forum for anyone interested:
- https://ethresear.ch/t/execution-consensus-client-bootnodes/14588
- https://research.lido.fi/t/execution-consensus-client-bootnodes/4449

FWIW, if you go into the EL clients, they are documented as well in the codebase; e.g. [Geth](https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go#L23-L29C1):

```go
// MainnetBootnodes are the enode URLs of the P2P bootstrap nodes running on
// the main Ethereum network.
var MainnetBootnodes = []string{
	// Ethereum Foundation Go Bootnodes
	"enode://d860a01f9722d78051619d1e2351aba3f43f943f6f00718d1b9baa4101932a1f5011f16bb2b1bb35db20d6fe28fa0bf09636d26a87d31de9ec6203eeedb1f666@18.138.108.67:30303", // bootnode-aws-ap-southeast-1-001
	"enode://22a8232c3abc76a16ae9d6c3b164f98775fe226f0917b0ca871128a74a8e9630b458460865bab457221f1d448dd9791d24c4e5d88786180ac185df813a68d4de@3.209.45.79:30303",   // bootnode-aws-us-east-1-001
	"enode://2b252ab6a1d0f971d9722cb839a42cb81db019ba44c08754628ab4a823487071b5695317c8ccd085219c3a03af063495b2f1da8d18218da2d6a82981b45e6ffc@65.108.70.101:30303", // bootnode-hetzner-hel
	"enode://4aeb4ab6c14b23e2c4cfdce879c04b0748a20d8e9b59e25ded2a08143e265c6c25936e74cbc8e641e3312ca288673d91f2f93f8e277de3cfa444ecdaaf982052@157.90.35.166:30303", // bootnode-hetzner-fsn
}
```

All the links to the other client bootnodes docs you can find in the ethresear.ch thread.

**Comment by pcaversaccio** [comment]
following up again: can we get this merged @zah @terencechain?

**Pull request merged**
