### PR TITLE
remove `prater` config as it has been copied to separate repo

### PR DESCRIPTION
**Pull request by etan-status**
A copy of the `prater` network definition is also available in the dedicated `goerli` repo. To avoid having multiple copies of the same data that have to be maintained separately, remove the `prater` config from this repo.

- https://github.com/eth-clients/goerli
- https://github.com/eth-clients/goerli/pull/179

### CODE REVIEW

**Comment by etan-status** [comment]
This is in line with how sepolia / holesky are handled (separate repos).

Mainnet should eventually also be moved to a separate repo, eth2-networks description specifically mentions that this repo is for test networks.

**Review by g11tech — APPROVED** [review]
+1 lgtm

**Review by parithosh — APPROVED** [review]

**Comment by parithosh** [comment]
I'll let you merge it once the Nimbus PRs have gone in @etan-status

**Comment by etan-status** [comment]
It's fine @parithosh , Nimbus locks all submodules to specific commits, so the version that we locked still contains the `prater` defs.

For the purpose of tracking what you referred to, this is the PR switching `prater` to the new `goerli` repo in Nimbus:

- https://github.com/status-im/nimbus-eth2/pull/5680

**Pull request merged**
